-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 18:32:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema id21360041_friendconnection_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id21360041_friendconnection_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id21360041_friendconnection_db` DEFAULT CHARACTER SET utf8 ;
USE `id21360041_friendconnection_db` ;

-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`departaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`departaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departament` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`citys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`citys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NOT NULL,
  `id_departament` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_citys_departaments1_idx` (`id_departament` ASC) ,
  CONSTRAINT `fk_citys_departaments1`
    FOREIGN KEY (`id_departament`)
    REFERENCES `id21360041_friendconnection_db`.`departaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`genders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `phone` VARCHAR(13) NULL,
  `birthdate` VARCHAR(45) NULL,
  `id_city` INT NULL,
  `id_gender` INT NULL,
  `picture` VARCHAR(500) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_citys1_idx` (`id_city` ASC) ,
  INDEX `fk_users_gender1_idx` (`id_gender` ASC) ,
  INDEX `fk_users_states1_idx` (`id_state` ASC) ,
  CONSTRAINT `fk_users_citys1`
    FOREIGN KEY (`id_city`)
    REFERENCES `id21360041_friendconnection_db`.`citys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_gender1`
    FOREIGN KEY (`id_gender`)
    REFERENCES `id21360041_friendconnection_db`.`genders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_states1`
    FOREIGN KEY (`id_state`)
    REFERENCES `id21360041_friendconnection_db`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`publications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `picture` VARCHAR(500) NULL,
  `date` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publications_users_idx` (`id_user` ASC) ,
  INDEX `fk_publications_states1_idx` (`id_state` ASC) ,
  CONSTRAINT `fk_publications_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `id21360041_friendconnection_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_states1`
    FOREIGN KEY (`id_state`)
    REFERENCES `id21360041_friendconnection_db`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(800) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `id_publication` INT NOT NULL,
  `id_user` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`id_user` ASC) ,
  INDEX `fk_comments_states1_idx` (`id_state` ASC) ,
  INDEX `fk_comments_publications1_idx` (`id_publication` ASC) ,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `id21360041_friendconnection_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_states1`
    FOREIGN KEY (`id_state`)
    REFERENCES `id21360041_friendconnection_db`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_publications1`
    FOREIGN KEY (`id_publication`)
    REFERENCES `id21360041_friendconnection_db`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `id_publication` INT NOT NULL,
  `id_user` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`id_user` ASC) ,
  INDEX `fk_likes_states1_idx` (`id_state` ASC) ,
  INDEX `fk_likes_publications1_idx` (`id_publication` ASC) ,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `id21360041_friendconnection_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_states1`
    FOREIGN KEY (`id_state`)
    REFERENCES `id21360041_friendconnection_db`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_publications1`
    FOREIGN KEY (`id_publication`)
    REFERENCES `id21360041_friendconnection_db`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id21360041_friendconnection_db`.`codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id21360041_friendconnection_db`.`codes` (
  `email` VARCHAR(100) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
